on:
  schedule:
    - cron:  "00 23 * * *" # Every day at 11:00pm UTC (4:00pm Pacific)'
  workflow_dispatch:

name: scripts

jobs:
  run-r-script:
    runs-on: MacOS # use MacOS to get around the libCurl issues
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      # imports an action from another repository, 
      # that enables the machine
      # to access the code inside our repository
      - uses: actions/checkout@v3 
      # imports an action from another repository, 
      # that installs R on the machine
      - uses: r-lib/actions/setup-r@v2
        with:
          # uses the RStudio Package Manager
          use-public-rspm: true
          
          # Set-up R
      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          
      - name: Execute Script
        # executes the RScript stored in the file
        run: |
          source("Premier_League_Sims_Script.R")
        
      - name: Commit files # Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "update data" && git push)
